### ISSUE TITLE
Provide Artifacts from Maven Repository

### ISSUE THREAD

**Issue by aemaem** [s-webber/projog#119]
Are there any plans on releasing artifacts to Maven?

**Comment by s-webber** [comment]
Thank you for raising this.

In response to your question I have requested the creation of a Projog repository. Once this has been done then I will deploy the latest artifacts to it, and update this issue with the details.

**Comment by s-webber** [comment]
This project is now available as a Maven artifact:

```
<dependency>
   <groupId>org.projog</groupId>
   <artifactId>projog-core</artifactId>
   <version>0.2.0</version>
</dependency>
```

The testing framework used by Projog is also available as a Maven artifact:

```
<dependency>
   <groupId>org.projog</groupId>
   <artifactId>projog-test</artifactId>
   <version>0.2.0</version>
   <scope>test</scope>
</dependency>
```

For examples of using both `projog-core` and `projog-test` please see:

https://github.com/s-webber/projog-examples

Thank you for suggesting this enhancement. If there are any other enhancements you would like (or you are aware of any bugs) then please raise a new issue.

Incidentally, since this issue was raised there has been another change made (#120) which means Projog no longer writes Java code generated at runtime to the filesystem, and no longer requires the `projogGeneratedClasses` directory to be in the classpath.
