### ISSUE TITLE
ProjogException: code too large

### ISSUE THREAD

**Issue by morandad** [s-webber/projog#175]
Hello,

I have an instance of Projog and I'm trying to send it my projog's file:

```
 Projog p= new Projog (observer)
p.consultFile(new File(MY_PROJOG_FILE))
```
In the _ProjogSourceReader.java_ file, in the _parseFile_ method, I'm getting an exception:

> org.projog.core.ProjogException: Caught org.projog.core.ProjogException while attempting to compile class: org.projog.content_generated_at_runtime.CompiledPredicate1 with message: Cannot compile: org.projog.content_generated_at_runtime.CompiledPredicate1 source: package org.projog.content_generated_at_runtime;
> import org.projog.core.udp.compiler.*;
> import org.projog.core.udp.interpreter.*;
> import org.projog.core.udp.*;
> import org.projog.core.term.*;
> import org.projog.core.*;
> import static org.projog.core.term.NumericTermComparator.NUMERIC_TERM_COMPARATOR;
> import static org.projog.core.function.AbstractSingletonPredicate.toPredicate;
> // test_6/6
> public final class CompiledPredicate1 implements CompiledPredicate { 

The source of this exception is from the _JavaSourceCompiler.java_ file , in the method _compile_  -

> org.projog.core.ProjogException: Failed compilation of org.projog.content_generated_at_runtime.CompiledPredicate1 Error on line 19037 in /org/projog/content_generated_at_runtime/CompiledPredicate1.java:19037: error: code too large
> public final boolean evaluate() {
>                      ^

The size of MY_PROJOG_FILE is 58 kb.
I've tried to reduce the size of the file, and omitted some of the predicates, so the new size of the file was 41 kb , and it worked.
But I must have **all** the predicates in my projog file, and the above scenario was just for testing...

So it seems that the problem is with my projog file size-
1. How can I deal with it?
1.A.    Is there a restrict on the file size that can be used with through the projog? 
1.B .   Is there a way to split the original projog file to some parts, and send all of them to the _consultFile_ method? (in case of size limit).

2. Maybe the exception pointing on another things? (not just the file size)

I'll appreciate your help :) 
Thanks!

**Comment by s-webber** [comment]
Hello,

Projog does not enforce any hard limit on the size of the files it consults. I suspect the problem you are seeing is not due to the total size of the file your are consulting but is instead due to the complexity of one of the predicates defined in that file. I think that, in an attempt to compile the predicate to Java, Projog is generating Java source code that is too large for the Java compiler.

_Background information:_ Projog supports two modes - "compiled" mode and "interpreted" mode. The default mode is "compiled" mode. When operating in "compiled" mode Projog attempts to compile user-defined predicates to Java code at runtime. This is done to improve the performance when evaluating Prolog queries that use these predicates.

From the error messages in your description it appears that the Java code that Projog is generating for the `test_6` predicate is too large for Java to compile.

I have released a change that, when Projog fails to compile a user-defined predicate, will cause Projog to revert to "interpreted" mode when evaluating that specific predicate. Reverting to "interpreted" mode could cause the evaluation of queries that use the predicate to be less efficient - but depending on the contents of the predicate the effect may be negligible. Of course, a better solution would be to alter Projog to avoid it generating such complex source code but that would be difficult and so hopefully this workaround will be sufficient for your needs.

To use this latest version of Projog please update your Gradle or Maven file to use version `0.4.0-SNAPSHOT` of `projog-core`. e.g.:

```
<dependency>
  <groupId>org.projog</groupId>
  <artifactId>projog-core</artifactId>
  <version>0.4.0-SNAPSHOT</version>
</dependency>
```

or:

```
compile group: 'org.projog', name: 'projog-core', version:'0.4.0-SNAPSHOT'
```

----

Incidentally, you can configure Projog to always operate in "interpreted" mode by using a `ProjogProperties` as an argument to the `Projog` constructor.

Example of configuring a `Projog` instance to operate in "interpreted" mode:

```
ProjogProperties projogProperties = new ProjogDefaultProperties() {
  @Override
  public boolean isRuntimeCompilationEnabled() {
    return false;  // return false to indicate that it should operate in "interpreted" mode
  }
};
Projog p = new Projog(projogProperties);
```

Operating in "interpreted" mode will mean that Projog will never attempt to compile user-defined predicates to Java.

A disadvantage of using "interpreted" mode is that it may impact the performance of queries (but the exact differences will depend on the specific predicates and queries you are using).

An advantage of using "interpreted" mode is that you will avoid the initial overhead required by "compiled" mode to compile predicates to Java at runtime, meaning the start-up time should be quicker.

----

I hope this information is useful. If you still experience problems then please let me know.

Thanks.

**Comment by s-webber** [comment]
Glad I could help. I am now closing this issue.

If you experience any other problems with Projog then please let me know by raising a new issue. Thanks.
