### ISSUE TITLE
Comparison with iProlog?

### ISSUE THREAD

**Issue by breandan** [s-webber/projog#202]
Hi @s-webber, love what you're doing here, please keep up the great work! I am evaluating some different Prolog implementations for the JVM and am curious if you might be able to provide any insight how Projog compares to [iProlog](https://raw.githubusercontent.com/ptarau/iProlog/master/IP/doc/paper.pdf) or [Jinni](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.52.3148&rep=rep1&type=pdf)? Thank you!

**Comment by s-webber** [comment]
Hi @breandan 

Thank you for your kind comments.

I'm not familiar with iProlog or Jinni. I will take a look.

Unfortunately I do not have any documentation on Projog that is similar to the iProlog or Jinni documentation you provided. I've developed Projog on my own in my free time, rather than being the result of formal academic study.

I do have the following documentation which you're welcome to look at. It is a little out of date now as it still mentions a "compiled" mode that converts Prolog to Java bytecode. This mode has since been removed and Projog only works in "interpreted" mode:

https://github.com/s-webber/projog/files/3747706/projog_design_documentation.zip

Projog is implemented fully in Java. It has an [API](http://projog.org/calling-prolog-from-java.html) to allow Java code to interact with Prolog. Functionality written in Java can be made available for use from Prolog. This mechanism is used to implement the [built-in predicates](http://projog.org/prolog-predicates.html) provided by Projog. The following projects contain examples of how Projog can be used to integrate Java and Prolog:

https://github.com/s-webber/projog-examples
https://github.com/s-webber/prolog-wumpus-world
https://github.com/s-webber/prolog-expert-system

I'm sorry if the information I've provided here is not what you were hoping for. If you do have any specific questions then please let me know and I will do my best to answer them.

Thanks.

**Comment by s-webber** [comment]
The Projog website has been updated to include class diagrams and design decisions:

http://projog.org/class-diagrams.html
http://projog.org/design-decisions.html

The information on the website is more accurate then the documentation I linked to in my previous comment, which was a little out-of-date.

I will now close this issue. Thank you again for showing an interest in Projog. If you have any further questions or comments then please raise a new issue.
